services:
  api:
    depends_on:
      - postgres
    command: bash -c "echo 'Installing npm' && npm install && echo 'Running migrations' && npx prisma migrate dev && echo 'Running seeds' && npx prisma db seed && echo 'Starting server' && npm run dev"
