name: Build test back-end
on:
  pull_request:
    branches:
     - main
    paths:
      - 'back-end/**'
  push:
    branches:
     - main
    paths:
      - 'back-end/**'

jobs:
  test-back-end:
    name: run tests back-end
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Npm Install
      working-directory: ./back-end
      run: npm install

    - name: Testing
      working-directory: ./back-end
      run: npm run test