- name: Telegram Notify Update
  on:
    push:
      branches:
       - main

  jobs:
    notify:
      name: notify
      runs-on: ubuntu-latest
      steps:
        - name: send telegram message on main update
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              Main updated with: "${{ github.event.head_commit.message }}"
